### ISSUE TITLE
NFR19. Upload of Post After 20 Minutes

### ISSUE THREAD

**Issue by nadinraz** [WSU-4110/Lost_and_Found#18]
| Feature Name         | NFR19. Upload of Post After 20 Minutes                        |
|----------------------|--------------------------------------------------|
| Goal                 | The system will upload a users’ post into the feed after 20 minutes of creation |
| Stakeholders         | Wayne State University’s Associates              |
| Description          | When users create a post for a lost item, there will be a 20 minute waiting period before the post gets uploaded to the feed. This ensures that if the user did not actually lose the item like he thought he did and ends up finding it before 20 minutes, then the feed will not have an unnecessary post |
| Origin               | Team members came up with this at our second meeting to decrease the amount of unnecessary posts on the feed. |
| Version              | 1.0  |
| Date                 | 09/18/2023       |
| Priority             | 4              |

**Comment by AhmedMinhajEmon** [comment]
This feature is no longer needed cause our OTP system will allow only wayne.edu mail. Any malicious post can be easily tracked.
