### ISSUE TITLE
FR7: Show User's Chat List 

### ISSUE THREAD

**Issue by yiliyavas** [WSU-4110/Lost_and_Found#7]
| Feature Name         | FR7. Show User's Chat List                         |
|----------------------|--------------------------------------------------|
| Goal                 | To display all existing chats for the current user.  |
| Stakeholders         | Wayne State University’s Associates and Administrators         |
| Description          | Users should be able to have multiple chats at the same time. Since all chats will be post related, users need easy access to those chats so that they can continue messaging with other users about lost items. There is also a plan to show if there are any new unread messages. |
| Origin               | Based after reviewing initial vision, so that users can be more accessible to communicate so that items can be found. |
| Version              | 1.0  |
| Date                 | 09/18/2023       |
| Priority             | 1             |

**Comment by AhmedMinhajEmon** [comment]
The chat feature has been changed into a comment feature. so closed
